import { StyleSheet } from "react-native";

export const ActiveWorkoutScreenstyles = StyleSheet.create({
    container: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 12,
      fontSize: 16,
      color: '#fff',
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 8,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    titleContainer: {
      flex: 1,
      alignItems: 'center',
    },
    workoutName: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#fff',
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    timerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    timerText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
      marginLeft: 4,
    },
    progressContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginBottom: 16,
    },
    progressBar: {
      flex: 1,
      height: 6,
      backgroundColor: 'rgba(255, 255, 255, 0.3)',
      borderRadius: 3,
      marginRight: 10,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      backgroundColor: '#5D3FD3',
      borderRadius: 3,
    },
    progressText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    exerciseHeader: {
      alignItems: 'center',
      marginVertical: 8,
      paddingHorizontal: 16,
    },
    exerciseIconContainer: {
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    exerciseName: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#fff',
      textAlign: 'center',
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    detailsCard: {
      backgroundColor: 'rgba(255, 255, 255, 0.85)',
      borderRadius: 16,
      marginHorizontal: 16,
      marginVertical: 16,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    detailRow: {
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    detailItem: {
      alignItems: 'center',
      flex: 1,
    },
    detailValue: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#5D3FD3',
    },
    detailLabel: {
      fontSize: 12,
      color: '#666',
      marginTop: 4,
      fontWeight: '600',
      letterSpacing: 1,
    },
    detailSeparator: {
      width: 1,
      height: '100%',
      backgroundColor: '#ddd',
    },
    completeButton: {
      backgroundColor: '#5D3FD3',
      paddingVertical: 16,
      borderRadius: 30,
      marginHorizontal: 16,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    completeButtonText: {
      fontSize: 18,
      color: '#fff',
      textAlign: 'center',
      fontWeight: 'bold',
    },
    navigationButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginHorizontal: 16,
      marginBottom: 20,
    },
    navButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.85)',
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 30,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    navButtonDisabled: {
      backgroundColor: 'rgba(255, 255, 255, 0.5)',
    },
    navButtonText: {
      fontSize: 16,
      color: '#5D3FD3',
      marginHorizontal: 4,
      fontWeight: '600',
    },
    navButtonTextDisabled: {
      color: '#aaa',
    },
    nextExerciseContainer: {
      marginHorizontal: 16,
      marginBottom: 20,
      backgroundColor: 'rgba(255, 255, 255, 0.85)',
      padding: 16,
      borderRadius: 16,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    nextExerciseLabel: {
      fontSize: 12,
      color: '#666',
      fontWeight: '600',
      letterSpacing: 1,
    },
    nextExerciseName: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#5D3FD3',
      marginTop: 4,
    },
    restContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    restTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#fff',
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    restTimer: {
      fontSize: 64,
      fontWeight: 'bold',
      color: '#fff',
      marginVertical: 20,
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    restNextExercise: {
      fontSize: 18,
      color: '#fff',
      marginBottom: 30,
      textAlign: 'center',
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    skipButton: {
      backgroundColor: 'rgba(255, 255, 255, 0.3)',
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: '#fff',
    },
    skipButtonText: {
      fontSize: 16,
      color: '#fff',
      fontWeight: '600',
    },
    finishWorkoutButton: {
      backgroundColor: 'rgba(255, 255, 255, 0.85)',
      paddingVertical: 14,
      borderRadius: 30,
      marginHorizontal: 16,
      marginVertical: 20,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    finishWorkoutText: {
      fontSize: 16,
      color: '#5D3FD3',
      textAlign: 'center',
      fontWeight: 'bold',
    },
    completedContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    completedTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#fff',
      marginVertical: 20,
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    statsCard: {
      backgroundColor: 'rgba(255, 255, 255, 0.85)',
      borderRadius: 16,
      width: '100%',
      padding: 20,
      marginBottom: 40,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    statRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginVertical: 8,
    },
    statLabel: {
      fontSize: 16,
      color: '#666',
    },
    statValue: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#5D3FD3',
    },
    finishButton: {
      backgroundColor: '#5D3FD3',
      paddingVertical: 16,
      paddingHorizontal: 32,
      borderRadius: 30,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    finishButtonText: {
      fontSize: 18,
      color: '#fff',
      fontWeight: 'bold',
    },
  });
  
